/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-tint": "#116a61",
                "on-error": "#ffffff",
                "on-tertiary-fixed-variant": "#49473f",
                "surface-dim": "#e1d8d4",
                "on-tertiary-container": "#fcf6ec",
                "surface-container": "#f5ece8",
                "error-container": "#ffdad6",
                "primary-container": "#2d7d74",
                "inverse-on-surface": "#f8efea",
                "secondary": "#954912",
                "tertiary-fixed": "#e7e2d8",
                "primary-fixed": "#a4f1e5",
                "outline": "#6f7977",
                "surface-variant": "#eae1dc",
                "on-primary-container": "#d7fff8",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "primary": "#03645c",
                "inverse-primary": "#88d4c9",
                "secondary-container": "#fd9b5e",
                "primary-fixed-dim": "#88d4c9",
                "error": "#ba1a1a",
                "surface-container-highest": "#eae1dc",
                "on-surface-variant": "#3f4947",
                "on-primary-fixed-variant": "#005049",
                "inverse-surface": "#34302d",
                "on-tertiary-fixed": "#1d1b16",
                "tertiary-container": "#747169",
                "on-surface": "#1f1b18",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#fbf2ed",
                "on-secondary-fixed-variant": "#753400",
                "on-background": "#1f1b18",
                "on-secondary": "#ffffff",
                "on-secondary-fixed": "#321200",
                "outline-variant": "#bec9c6",
                "surface-bright": "#fff8f5",
                "on-secondary-container": "#733300",
                "secondary-fixed": "#ffdbc9",
                "on-primary-fixed": "#00201d",
                "tertiary-fixed-dim": "#cbc6bd",
                "tertiary": "#5c5951",
                "secondary-fixed-dim": "#ffb68c",
                "surface": "#fff8f5",
                "background": "#fff8f5",
                "surface-container-high": "#efe6e2",
                "on-primary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-sm": "8px",
                "card-padding": "20px",
                "base": "4px",
                "margin-page": "32px",
                "gutter": "24px",
                "stack-lg": "24px",
                "stack-md": "16px"
            },
            "fontFamily": {
                "sans": ["Inter", "sans-serif"],
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
                "headline-xl": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"]
            },
            "fontSize": {
                "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
                "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
            }
        },
    },
};
